name: CI
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches: [devel]
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true
jobs:
  # build-server:
  #   uses: dbeaver/dbeaver-common/.github/workflows/mvn-package.yml@devel
  #   name: Check
  #   secrets: inherit
  #   with:
  #     mvn-args: -Dplain-api-server -Dheadless-platform
  #     project-directory: ./cloudbeaver/server/product/aggregate
  #     project-deps: ./cloudbeaver/project.deps
  #     timeout-minutes: 5
  build-server:
    name: Server
    uses: ./.github/workflows/backend-build.yml
    secrets: inherit
  build-frontend:
    name: Frontend
    uses: ./.github/workflows/frontend-build.yml
    secrets: inherit
  lint-server:
    name: Server
    uses: dbeaver/dbeaver-common/.github/workflows/java-checkstyle.yml@devel
    secrets: inherit
  lint-frontend:
    name: Frontend
    uses: ./.github/workflows/frontend-lint.yml
    secrets: inherit
  call-docker-build-and-push:
    name: Run
    needs: [build-server, build-frontend]
    uses: ./.github/workflows/docker-build-and-push.yml
